module PartitionGardener
  VERSION: String

  MOVE_BATCH_SIZE: Integer
  FUTURE_MONTH_PARTITION_ROW_THRESHOLD: Integer
  DEFAULT_STATEMENT_TIMEOUT: ActiveSupport::Duration

  def self.run!: (
    ?statement_timeout: ActiveSupport::Duration,
    ?job_class_name: String,
    ?continue_on_error: bool,
    ?dry_run: bool,
    ?table_name: String?
  ) -> untyped

  def self.audit: (String table_name) -> untyped
  def self.plan: (?table_name: String?, ?config: Hash[Symbol, untyped]?) -> untyped
  def self.maintenance_for: (Hash[Symbol, untyped] config, ?job_class_name: String) -> untyped
end
